services:
  bot:
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_URI: mongodb://mongo:27017
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    container_name: bot
    dns:
      - 8.8.8.8
      - 8.8.4.4
    networks:
      caddy_net:
        aliases:
          - bot

networks:
  caddy_net:
    external: true
